# Generated by Django 3.0.7 on 2020-07-02 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=datetime.datetime.today, upload_to=None),
            preserve_default=False,
        ),
    ]
