# Generated by Django 3.0.7 on 2020-09-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200921_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_photo', to='blog.Article')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
