# Generated by Django 3.0.7 on 2020-09-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200928_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article_photo', to='blog.Article'),
        ),
    ]
