# Generated by Django 3.0.7 on 2020-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200928_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='first_photo',
            field=models.BooleanField(default=False),
        ),
    ]
