# Generated by Django 3.0.7 on 2020-12-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_picture_first_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='only_article',
            field=models.BooleanField(default=False),
        ),
    ]
