# Generated by Django 3.0.7 on 2021-02-14 07:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210204_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
