# Generated by Django 3.0.7 on 2021-02-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
